import type { EditorCommand } from "../commands";
import { createInventoryPanelCommands } from "../prefab";
import { createAiProposal } from "./AiProposal";
import type { AiProposal } from "./AiProposal";
import type { AiProposalContext } from "./AiContext";
import { enabledMemory, summarizeMemoryForAi } from "./PreferenceMemory";
import { getAiComponentSchemas, summarizePrefabForAi } from "./ai";

function includesAny(text: string, words: string[]) {
    return words.some((word) => text.includes(word));
}

function selectedOrDefault(context: AiProposalContext) {
    return context.selection || context.prefab.root.key || context.prefab.root.id || context.prefab.root.name || 'root';
}

export function createMockAiCommands(prompt: string, context: AiProposalContext): EditorCommand[] {
    const commands: EditorCommand[] = [];
    const lower = prompt.toLowerCase();
    const target = selectedOrDefault(context);

    if (includesAny(lower, ['inventory', 'backpack', '背包', '物品栏'])) {
        commands.push(...createInventoryPanelCommands({
            parent: target,
        }));
        return commands;
    }

    if (includesAny(lower, ['start game', '开始游戏', '开始', 'start'])) {
        commands.push({
            op: 'setComponentProp',
            node: 'submitButtonLabel',
            component: 'text',
            prop: 'text',
            value: lower.includes('continue') ? 'Continue' : 'Start Game',
        });
    }

    if (includesAny(lower, ['center', '居中', '中间', '中心'])) {
        commands.push({
            op: 'setTransform',
            node: target,
            values: {
                x: 320,
                y: 192,
            },
        });
    }

    if (includesAny(lower, ['blue', '蓝色', 'primary'])) {
        commands.push({
            op: 'setComponentProp',
            node: target,
            component: 'bg',
            prop: 'color',
            value: context.designTokens?.colors?.primary ?? 0x2563eb,
        });
    }

    return commands;
}

export function createMockAiProposal(prompt: string, context: AiProposalContext, source = 'MockAiProposalProvider'): AiProposal {
    const commands = createMockAiCommands(prompt, context);
    const summary = summarizePrefabForAi(context.prefab);
    const schemas = getAiComponentSchemas();
    const memorySummary = summarizeMemoryForAi(enabledMemory(context.memory ?? []));

    return createAiProposal({
        prompt,
        explanation: commands.length > 0
            ? `${source} generated ${commands.length} command(s) from the prompt using ${schemas.length} registered component schemas.${context.actions?.length ? ` Actions: ${context.actions.map((action) => action.key).join(', ')}.` : ''}${memorySummary ? ` Memory:\n${memorySummary}` : ''}`
            : `${source} could not infer a concrete edit for "${prompt}".`,
        commands,
        annotations: [{
            node: context.selection ?? summary.root.key ?? summary.root.id,
            message: `Generated by ${source}; replace this provider to call a real model.`,
        }],
        risks: commands.length === 0 ? ['No commands were generated from this prompt.'] : [],
    });
}
